# Generated by Django 4.2.6 on 2024-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
