# Generated by Django 4.2.6 on 2024-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tranrec_alter_record_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cusdes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prodes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TranSacRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('totamt', models.BigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
